// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogtyvtgimusfaybannlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ndHl2dGdpbXVzZmF5YmFubmxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDg2OTAsImV4cCI6MjA2OTA4NDY5MH0.8rdCAxrnfk8XY0KH1fREqaiVgL35VEpypXArPXc78hU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});